model_list:
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "https://api.openai.com/v1"
  - model_name: vllm-qwen3-8b
    litellm_params:
      model: Qwen/Qwen3-8B
      api_key: "none"
      api_base: "http://0.0.0.0:8050/v1"